import sys, io, json
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8', errors='replace')
import requests

vid = "Wercpk28guY"
proxies = {'http': 'http://127.0.0.1:2081', 'https': 'http://127.0.0.1:2081'}
headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/120.0 Safari/537.36'}

instances = [
    "https://pipedapi.kavin.rocks",
    "https://api.piped.private.coffee",
    "https://pipedapi.adminforge.de",
    "https://piapi.ggtyler.dev",
]

for base in instances:
    try:
        r = requests.get(f"{base}/streams/{vid}", proxies=proxies, headers=headers, timeout=25)
        print(f"{base}: status={r.status_code} len={len(r.text)}")
        if r.status_code == 200:
            data = r.json()
            print("  title:", data.get("title"))
            subs = data.get("subtitles", [])
            print("  subtitles:", json.dumps([{k: s.get(k) for k in ('code','autoGenerated','name')} for s in subs], ensure_ascii=False))
            # find en subtitle
            target = None
            for s in subs:
                if s.get("code") in ("en", "en-US") or "en" in (s.get("code") or ""):
                    target = s
                    break
            if target is None and subs:
                target = subs[0]
            if target:
                url = target["url"]
                if url.startswith("/"):
                    url = base + url
                rc = requests.get(url, proxies=proxies, headers=headers, timeout=30)
                print(f"  subtitle fetch: status={rc.status_code} len={len(rc.text)}")
                if rc.status_code == 200 and len(rc.text) > 100:
                    with open(r"D:\Project\dsh_rally_cars\_tmp_captions.vtt", "w", encoding="utf-8") as f:
                        f.write(rc.text)
                    print("  SAVED. first 400:")
                    print(rc.text[:400])
                    break
    except Exception as e:
        print(f"{base}: ERR {type(e).__name__} {e}")
